import { Poppins } from "next/font/google";
import "./globals.css";


export const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata = {
  title: "Table Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased px-6`}
      >
        {children}
      </body>
    </html>
  );
}
